# Generated by Django 4.0.6 on 2022-07-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_alter_post_options_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
